### ISSUE TITLE
Thumbnail API timeouts

### ISSUE THREAD

**Issue by asim** [m3o/m3o#28] opened 2021-10-27 08:21 UTC
The thumbnail API is timing out and throwing tons of errors. Related to memory usage and some sort of permission denied issues. Need to look at rewriting to use some alternative backend or fixing the issue.

**Comment by domwong** [comment] 2021-11-04 10:14
Process leak caused by chromium. Fixed in https://github.com/micro/services/pull/257

**Closed by domwong** 2021-11-04 10:14 UTC
